### ISSUE TITLE
5/30

### ISSUE THREAD

**Issue by daniel128** [jack111331/BigBang#3]
OK:
	對沒有Miss的人Bang 會成功造成損血

Bug:
	(Server端送出玩家可選的2個角色時 高機率Client端會沒有收到訊息)
	Action 13會造成當機 且打出Action 13的人會Receive Action 17之後 有時只會在自己這邊再跑一次Action 7
	對El Gringo攻擊之後 自己的牌少了一張 但El Gringo卻沒有增加
	對有Miss的人攻擊之後 會正確跑出可用牌 以及是否使用 但是不論是否使用之後就卡住了(沒crash)

**Comment by jack111331** [comment]
Action 13修復回覆Action 17的內容
El Gringo確實沒效果 這方面還在看原因
對有miss的人攻擊後 正確跑出可用牌並解決卡住問題 可以再測測看

**Comment by jack111331** [comment]
El Gringo被攻擊到後已經可以隨機抽目標卡到自己身上
你測完沒問題後可以自己close ww
